# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e19e5ae80958a3cd2e4a0da973d8c9d5ad61bb0134385c459a408fbac0f44b11b5e97d0a839ffc7085c0e70fa22934289bccf2cd6663ea14d7916749d4828c8

test:
  secret_key_base: 9402d03f88978df51f147e7ccecaabfcc2cd876092dae4f39523fabe0ae0f005c3e2dca35e1edfe67dcac6952b2b2b9b1dbf6be46accd57937ffda3d86a9919b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
